[package]
name = "playground-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "playground_macros"
crate-type = ["rlib", "cdylib"]

[dependencies]
ts_macro_host = { path = "../../crates/ts_macro_host" }
ts_macro_abi = { path = "../../crates/ts_macro_abi" }
inventory = "0.3"
ts_macro_derive = { path = "../../crates/ts_macro_derive" }
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
serde-wasm-bindgen = "0.6"
